provider = "Stork"
ticker = "INJ/USDT"
pullInterval = "1m"
oracleType = "Stork"
url = "wss://dev.api.stork-oracle.network/evm/subscribe"
header = ""
message = "{\"type\":\"subscribe\",\"trace_id\":\"123\",\"data\":[\"BTCUSD\"]}"