name: Release docker images
on:
  push:
    tags:
      - v**

permissions:
  id-token: write
  contents: read

env:
  ECR_ENABLED: true
  ECR_REPO: public.ecr.aws/l9h3g6c6/injective-price-oracle
  GHCR_ENABLED: false
  GHCR_REPO: ghcr.io/injectivelabs/injective-price-oracle

jobs:
  multi-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout injective-price-oracle
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Log-in to ghcr.io
        if: env.GHCR_ENABLED == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::981432137740:role/injective-price-oracle
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
        
      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build
        run: |
          TAG=${{ github.ref_name }}
          [[ $ECR_ENABLED == "false" ]] || docker buildx build --tag $ECR_REPO:$TAG --tag $ECR_REPO:latest --platform linux/amd64 --push .
          [[ $GHCR_ENABLED == "false" ]] || docker buildx build --tag $GHCR_REPO:$TAG --tag $GHCR_REPO:latest --platform linux/amd64 --push .
