provider = "injective_plf_oracle"
ticker = "TIA/USDT"
pullInterval = "1m"
observationSource = """
   ticker [type=http method=GET url="https://testnet.plf-oracle.injective.network/v1/price?symbol=TIA/USDT"];
   parsePrice [type="jsonparse" path="price"]

   ticker -> parsePrice 
"""
